---

window:
  height: 500
  width:  320

splits:
  text-when-empty: "-"
  total-splits: 10
  upcoming-splits: 3
  col1: "delta"
  col2: "comparison"
  lock-last-split: true
  decimals-before-1-min: true
  decimals-after-1-min: false

timer:
  leading-zeros: false
  decimals: 1

metadata:
  show-prev-seg-against-best: true
  show-possible-timesave: true
  show-sum-of-best: true

colors:
  normal-text: "#eee"
  highlight:   "#eb2"
  background:  "#222"
  ahead:       "#6f6"
  behind:      "#f66"
  best-seg:    "#eb2"
  new-time:    "#eee"

hotkeys:
  split: " "
  reset: "-"
  pause: "p"
  next:  "down"
  prev:  "up"
